cabinetoffice/national-leadership-centre-drupal

- config/sync/bevan.settings.yml
- config/sync/block.block.bevan_admin.yml
- config/sync/block.block.bevan_branding.yml
- config/sync/block.block.bevan_breadcrumbs.yml
- config/sync/block.block.bevan_local_actions.yml
- config/sync/block.block.bevan_local_tasks.yml
- config/sync/block.block.bevan_mainnavigation.yml
- config/sync/block.block.bevan_messages.yml
- config/sync/block.block.bevan_page_title.yml
- config/sync/block.block.bevan_tools.yml
- config/sync/block.block.footer.yml
- config/sync/block.block.govuk_design_system_branding.yml
- config/sync/block.block.govuk_design_system_content.yml
- config/sync/block.block.govuk_design_system_footer.yml
- config/sync/block.block.govuk_design_system_local_actions.yml
- config/sync/block.block.govuk_design_system_local_tasks.yml
- config/sync/block.block.govuk_design_system_messages.yml
- config/sync/block.block.govuk_design_system_page_title.yml
- config/sync/block.block.mainpagecontent.yml
- config/sync/core.extension.yml
- config/sync/govuk_design_system.settings.yml
- config/sync/system.theme.yml
- web/themes/custom/bevan/bevan.info.yml
beware of base theme npm install requirements
> Adds Bevan subtheme of GOV.UK Design System theme

- composer.lock
> Update Select or Other contrib module 8.x-1.0-alpha3 » 8.x-1.0-alpha4

- web/modules/custom/nlc_prototype/nlc_prototype.module
> Update name module values when separate fields are updated

- config/sync/block.block.mainpagecontent.yml
- config/sync/block.block.views_block__current_role_block_1.yml
- config/sync/core.date_format.simple_date.yml
- config/sync/core.entity_form_display.node.organisation.default.yml
- config/sync/core.entity_view_display.node.organisation.default.yml
- config/sync/core.entity_view_display.profile.role.default.yml
- config/sync/core.entity_view_display.profile.role.teaser.yml
- config/sync/core.entity_view_display.user.user.compact.yml
- config/sync/core.entity_view_display.user.user.default.yml
- config/sync/field.field.node.organisation.field_address.yml
- config/sync/field.storage.node.field_address.yml
- config/sync/salesforce_mapping.salesforce_mapping.network_individual_user_mapping.yml
- config/sync/salesforce_mapping.salesforce_mapping.network_organisation_mapping.yml
- config/sync/views.view.current_role.yml
> Salesforce mapping for Organisation content type [ch490]

- web/sites/default/settings.prod.php
[ch594]
bonus: ensure devel config environment is off
> Set the Sendgrid API key in settings file, from env var

- config/sync/system.site.yml
> Update the NLC name

- composer.lock
- config/sync/views.view.profiles.yml
> Update Drupal Core 8.7.8 > 8.7.10, with dependencies

- composer.lock
- Config Filter 8.x-1.4 > 8.x-1.5
- Field Group 8.x-3.0-rc1 > 8.x-3.0-rc2
- Mail System 8.x-4.1 > 8.x-4.2
- S3 File System 8.x-3.0-alpha13 > 8.x-3.0-alpha14
- Search API 8.x-1.14 > 8.x-1.15
> Update a bunch of contrib modules [ch710]

- web/modules/custom/nlc_prototype/nlc_prototype.module
> User entity fields `field_first_name` and `field_last_name` no longer exist, remove this nlc_prototype_user_presave()

- docker-compose.yml
> Update docker-compose to add a named network for nlc_cms [ch809]

- web/themes/custom/bevan/templates/form/form-element.html.twig
- web/themes/custom/bevan/templates/layout/page.html.twig
This fixes both 763 and 770
[ch763]
[ch770]
> General accessibility fixes

- .env.example
- README.md
- docker-compose.yml
- phpunit.xml
- web/modules/custom/nlc_prototype/tests/src/Functional/NlcUserOneTimeLoginLinkTest.php
- web/modules/custom/nlc_prototype/tests/src/Unit/NlcUserAuthTest.php
[ch1036]
One of the functional tests fails at the moment (the first one) and I'm not sure why, but I don't want that to stop adding this to the codebase and blocking work being done by @stutily to build a test platform
> Initial rudimentary functional and unit tests, with config, env, and README

- config/sync/core.entity_form_display.taxonomy_term.job_title.default.yml
- config/sync/core.entity_form_display.taxonomy_term.region.default.yml
- config/sync/core.entity_form_display.taxonomy_term.sector.default.yml
- web/sites/default/settings.php
Story details: https://app.clubhouse.io/nationalleadershipcentre/story/1359
cf. also 36b1205
> HOTFIX: dev code added to settings.php in 36b1205 merged to master causes DB connection errors on deploy

- config/devel/google_analytics.settings.yml
- config/sync/google_analytics.settings.yml
- web/modules/custom/nlc_prototype/js/nlc_prototype.google_analytics.js
… that does not send link email address to GA [ch881]
> Turns of GA contrib mailto link tracking; adds custom mailto link tracking [ch881]

- config/sync/views.view.directory.yml
This updates the DB search zero results message to match that already set in the Elastic Search view.
> Update zero results message

- config/sync/system.site.yml
- config/sync/user.settings.yml
Don't tell users that we've created account
> Disable new account notification

- config/sync/core.entity_view_display.user.user.default.yml
Simple config change to remove that field.
> Hide register interest field

- web/themes/custom/bevan/js/collapsiblock.js
> Place filter title accordion icons inside the title button, so they are clickable

- web/modules/custom/nlc_register_interest/js/nlc_register_interest.js
I didn't see your suggestion on #112 before closing it @DarkSnow. Updated now.
> Show more jump bug fix, but with event.preventDefault(); instead [ch1658]

- web/themes/custom/bevan/templates/navigation/views-mini-pager.html.twig
The corresponding ID was missing, added it in.
> Added id for label element

- web/modules/custom/nlc_prototype/src/Controller/DirectoryTokenAccessConfirmController.php
> Revert email address on directory access confirm page to plain text [ch1963]

- composer.json
- composer.lock
- config/sync/core.extension.yml
Story details: https://app.clubhouse.io/nationalleadershipcentre/story/2331
> Adds and enable drupal/health_check contrib contrib module [ch2331]

- config/sync/update.settings.yml
Stop it.
Story details: https://app.clubhouse.io/nationalleadershipcentre/story/2471
> Drupal is sending updates 'update available' emails to admin@example.com [ch2471]

- web/modules/custom/nlc_prototype/src/Form/DirectoryTokenAccessForm.php
This will allow us to filter error for nlc_prototype to see the log messages
> Log login failure

- .gitignore
- web/modules/custom/nlc_prototype/src/Form/DirectoryTokenAccessForm.php
- web/sites/default/settings.prod-eks.php
- web/sites/default/settings.prod.php
- web/sites/default/settings.stage.php
- web/sites/default/settings.staging-eks.php
(to production branch)
This is here to merge when you're ready with pod config @stutily
> Put compiled twig files in a directory that is not added to S3 [ch2513]

- composer.json
> New patch for salesforce to properly fix (?) SF token refresh [ch1996]

- web/modules/custom/nlc_prototype/src/Plugin/Block/Covid19EsurvSurveyBlock.php
Story details: https://app.clubhouse.io/nationalleadershipcentre/story/3177
> Change link on the survey banner [ch3177]

- composer.json
Cf. patch update at https://www.drupal.org/project/salesforce/issues/3120102#comment-13530142 (and suggestion in messages prior to that)
> Apply new patch for SF auth token refresh [ch1996]

- composer.lock
- web/themes/custom/bevan/package-lock.json
- web/themes/custom/bevan/package.json
Plus fix security alert in minimist npm package, in Bevan theme
> Chore: Drupal base theme update [ch3244]

- composer.json
- composer.lock
- web/modules/custom/nlc_prototype/src/Plugin/Block/Covid19EsurvSurveyBlock.php
- web/themes/custom/bevan/package-lock.json
- web/themes/custom/bevan/package.json
Plus also
- npm audit fix in bevan custom theme [ch3244]
- Apply new patch for SF auth token refresh [ch1996]
> Upgrade drupal/govuk_design_system 8.x-1.0-beta1 > 8.x-1.0-beta2 (production) [ch3244]

- composer.json
Updates to newer patch that passes tests for 8.8.x at https://www.drupal.org/project/drupal/issues/2825860#comment-13415651
> Update composer to apply newer patch for drupal/core views numeric filter bug [ch3765]

- composer.lock
All seems fine. Just one database update required.
```
------------ ------------------------ ------------- -------------------------------------------------------------- 
Module       Update ID                Type          Description                                                   
------------ ------------------------ ------------- -------------------------------------------------------------- 
search_api   fix_index_dependencies   post-update   Re-save Search API index configurations to fix dependencies.  
------------ ------------------------ ------------- -------------------------------------------------------------- 
```
And probably need to set items in the `individuals` index to be reindexed, then run the reindexing:
```
drush search-api:reset-tracker individuals
drush …
```
> Update contrib modules [ch4072]

- config/sync/structure_sync.data.yml
Will need a step added to the deployment builds
> Add footer + social menu data to structure sync [ch4063]

- composer.json
Cf. https://www.drupal.org/project/salesforce/issues/3134201#comment-13600201
> Update composer.json to apply patch for Salesforce Mapping DB static queries bug [ch4084]

- web/modules/custom/nlc_prototype/js/nlc_prototype.google_analytics.js
- web/themes/custom/bevan/templates/node/node--external-link--card.html.twig
Story details: https://app.clubhouse.io/nationalleadershipcentre/story/4446
> Connect Library: Analytics
